CADE_COM_APP/CADE_COM_APP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Community.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CADE_COM_APP/Community/urls.py
from django.urls import path

from .views import home_view

app_name = "Community"

urlpatterns = [
    path('', home_view, name="home"),
]

CADE_COM_APP/Community/models.py
import uuid

from django.db import models
from users.models import User


# Create your models here.

class Code(models.Model):
    code_file = models.FileField(upload_to='static/')
    commit = models.TextField(max_length=750, unique=True)
    commit_code = models.UUIDField(blank=True, default=uuid.uuid4())

    def __str__(self):
        return f'{self.code_file}'


class CodeBase(models.Model):
    name = models.CharField(max_length=120)
    code = models.ManyToManyField(Code)

    def __str__(self):
        return f'{self.name}'


class Projects(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=140, unique=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    codebase = models.ManyToManyField(CodeBase)
    slug = models.SlugField(default='')

    def __str__(self):
        return f'{self.name}'

CADE_COM_APP/users/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=120, unique=True)
    password = models.CharField(max_length=8, unique=True)
    email = models.EmailField(default='')
    profile_image = models.ImageField(default="User_Image/no_profile_image.jpg", unique=True)
    description = models.TextField(max_length=1000, blank=True, default='')

    def __str__(self):
        return f'{self.username}'

CADE_COM_APP/Community/views.py
from django.shortcuts import render


# Create your views here.
def home_view(request):
    return render(request, "home.html")

CADE_COM_APP/users/views.py
from django.shortcuts import render

# Create your views here.

CADE_COM_APP/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
    <link rel="stylesheet" href="static/style.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Community:home' %}">CADE_COM</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Marketplace</a>
        </li>
          <a class="nav-link" href="#">Explore</a>
        </li>
        </li>
          <a class="nav-link" href="#">Blog</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% block content %}{% endblock content %}
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</html>

CADE_COM_APP/templates/home.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CADE_COM{% endblock title %}</title>
</head>
<body>
<br>
{% block content %}
<br>
<main>
  <h1 class="visually-hidden">Sidebars examples</h1>

  <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link" aria-current="page">
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
          Home
        </a>
        <hr>
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
  </div>
    {% endblock content %}
</body>
</html>